### PR TITLE
answered

### PR DESCRIPTION
**Pull request by hyyyaaa**
answers to questions 1,2 and bonus

### CODE REVIEW

**Comment by ilkerg** [comment]
Sorry for asking, but are you enrolled in the course?
Your github username doesn't give much clue about your identity.
Also I don't think I have received an email regarding your github username, otherwise I would have invited you to the course organization.

**Comment by hyyyaaa** [comment]
Yes i am enrolled, sorry for the confusion, bugrahan sahin, 2011400183. I
did add it when github warned me of my identity when i tried to commit, but
its buried deep in github i guess.

2016-03-01 21:10 GMT+02:00 İlker Gündoğdu notifications@github.com:

**Comment by ilkerg** [comment]
Ok then, i'll invite you to the organization in a minute.

Some comments on the homework:
- Check the acceptance rate for p = 0.7 case. It seems you need to reset your counters.

> If we use rejection sampling, with increasing dimension the acceptance rate will drop.
- Yes it will drop, but what is the relationship between the average acceptance rate and the number of dimensions? Consider the volume of the unit n-sphere and the volume of the enclosing n-cube..

**Comment by hyyyaaa** [comment]
May i correct them now? i realised the relationship is the ratio of the
volumes, volume of n-sphere has r^n in its equation and since 0<=r<=1,
should i write the full equation.

2016-03-01 21:31 GMT+02:00 İlker Gündoğdu notifications@github.com:

**Comment by ilkerg** [comment]
Sure, you can make as many corrections as you need.

Just include the formula for the volume of the unit n-sphere and report the ratio for some n, e.g. 1 to 10.
You need to show that it is decreasing rapidly with increasing n.

**Comment by ilkerg** [comment]
:+1:

**Pull request closed without merging**
