### PR TITLE
Assignment 1 submission

### PR DESCRIPTION
**Pull request by dorukkilitcioglu**
Comments are welcome.

### CODE REVIEW

**Comment by ilkerg** [comment]
:+1: 
Very nice report, thanks for the effort.

Some comments:
- plt.axis('equal') helps your circles to look like circles instead of ellipses.
- If you use p=1.5 unit ball as a proposal for p = 0.7 and to obtain samples from the proposal use another rejection sampling scheme, this doesn't make the whole process more efficient. This just makes use of two rejection sampling schemes back to back, effectively making the 2-norm unit ball your proposal distribution. More effective proposal for p = 0.7 case would be to use 1-norm unit ball, which is simply a rotated square.
- Some parts of the code could be vectorized to achieve better performance and to decrease clutter (_e.g. p_norm_accepted, normalize_).

**Comment by alper111** [comment]
Let's say there are 5 points in the circle and 4 of them lie in the area defined by p=1.5 and 3 of them lie in the area defined by p=0.7. While the sample is drawn from p=2, only accepted points for p=1.5 (in this case 4 points) are used as a proposal for p=0.7. As if it is somehow managed to draw samples from p=1.5, then these points are used as a proposal.

So first proposal p=2 for p=0.7 -->> 3/5
Second proposal p=1.5 for p=0.7 -->> 3/4

So is it because we don't have a procedure for drawing from p=1.5 without rejection sampling ?

**Comment by dorukkilitcioglu** [comment]
Thanks for the feedback. @alper111's comment is exactly what I had in mind when doing that part of the assignment. My understanding of the acceptance rate/efficiency was:

> Given a proposed method of sampling (a proposal), what percentage of the generated samples lie in the desired sample?

Obviously, getting the samples from p = 1.5 adds an initial inefficiency and the whole scheme would therefore not be practical, but doesn't the p = 1.5 proposal technically has a higher efficiency than the p = 2 one? (I might be mistaken in mixing efficiency and acceptance rate here).

If p = 1.5 doesn't have a higher efficieny, that would mean calculating the efficiency requires us to know the efficiency of the proposal. Is that correct?

On another note, can you explain a bit what you mean by vectorizing the code? I did try to use some kind of `map this function over this list` function, but couldn't make it work properly (map function seems to be deprecated). I'm new to Python, so I did have to default to regular for loops at times.

**Comment by ilkerg** [comment]
Efficiency of a rejection sampling scheme can be defined in terms of the ratio between the samples drawn from the proposal distribution q(x) and the accepted ones, which lie under the target density, p(x). If you obtain samples from the proposal distribution via another rejection sampling scheme by using, say q'(x) as a proposal, than this effectively makes q'(x) the proposal for your original problem. Then acceptance rate of the whole rejection sampling scheme should be calculated by using p(x) and q'(x). In other words the intermediary step (using q(x)), would provide no help.

> @alper111: So is it because we don't have a procedure for drawing from p=1.5 without rejection sampling ?

I am not aware of any procedure other than rejection sampling for drawing uniform samples from arbitrary p-norm balls. Even if there is one, the point of that part of the homework was to demonstrate how an appropriately chosen proposal distribution affects the acceptance rate of the rejection sampling method. p = 1.5 ball doesn't count as an appropriate proposal for the p = 0.7 case, because obtaining samples from the p = 1.5 ball requires another rejection sampling application.

For p = 0.7, instead of using 2-norm ball as proposal you can try 1-norm ball, which is a rotated square. Therefore it shouldn't be difficult to draw uniform samples from the 1-norm ball (without using rejection sampling of course). Then you can compare using 2-norm ball and 1-norm ball as proposals for sampling uniformly from p = 0.7.

> @Xyllan: On another note, can you explain a bit what you mean by vectorizing the code?

`is_accepted` function can act on vector arguments by default because the functions inside (all numpy stuff) allow vector arguments. Therefore you can get rid of `p_norm_accepted` function altogether. A simple snippet could be something like this:

``` python
accepted = is_accepted(x, y, 1.5)
x1 = x[accepted]
y1 = y[accepted]
#x1, y1 = p_norm_accepted(x, y, 1.5)
```

Here `accepted` is a boolean array, therefore it could be used to subset the `x` and `y` arrays to obtain only the entries where `accepted = True`.

Hope that helps.

**Comment by dorukkilitcioglu** [comment]
@ilkerg I have updated the assignment as per the suggestions.

**Comment by ilkerg** [comment]
:+1:

**Pull request closed without merging**
