### PR TITLE
Cmpe548-Assignment1-2011400186.ipynb added

### PR DESCRIPTION
**Pull request by oeken**
title says it all

### CODE REVIEW

**Comment by ilkerg** [comment]
For the 2nd question you need to use 2-norm ball as proposal, not a square.
You can fix and commit / push if you like.

**Comment by oeken** [comment]
Thank you for the feedback

**Comment by ilkerg** [comment]
I didn't notice yesterday, but the method you used for the bonus part is not the one described in [hw1.pdf](https://github.com/Bogazici-CMPE548-Spring2016/Assignment-1/blob/master/hw1.pdf).
I'll keep the pull request open in case you'd like to change that part, which should be easier than the one you have implemented.

**Comment by oeken** [comment]
I have added the missing part.

**Comment by ilkerg** [comment]
:+1:

**Pull request closed without merging**
