### PR TITLE
Sinem Kafiloglu 2015800048

### PR DESCRIPTION
**Pull request by sinemkfl**
Homework 1 Code

### CODE REVIEW

**Comment by sinemkfl** [comment]
The figures are added and scaling is corrected. Is it ok?

**Comment by ilkerg** [comment]
Could you please include your plots in the notebook?
You don't have to save them in separate files.
just add `%matplotlib inline` as the first line in your first cell. That makes your plots to show up in the notebook.

**Comment by atcemgil** [comment]
Sinem

Use %matplotlib inline and just plot into the notebook so we can view things easily.

Please check the examples posted!

**Comment by ilkerg** [comment]
:+1:

**Pull request closed without merging**
